### ISSUE TITLE
Zealot of emacs

### ISSUE THREAD

**Issue by jinyangustc** [lianxiangru/clj-zhihu#1]
So you really try to do everything in emacs? lol

**Comment by lianxiangru** [comment]
我想在知乎上爬个妹子出来。现有的包没有对账户的操作功能，只好自己写了。

**Comment by jinyangustc** [comment]
Interesting. I'll send some pull requests if I know Clojure, but I don't :joy:. Maybe some test & bug report. lol

**Comment by lianxiangru** [comment]
haha! welcome! Python is another option. I chose clojure just because I
wanted to run machine learning algorithm in parallelism along with the I/O
of fetching information.

**Comment by jinyangustc** [comment]
难道是分手了吗，又开更了 lol

**Comment by lianxiangru** [comment]
只是看以前代码太丑了重构一下。。
